# Base image
FROM python:3.11-slim

# Ensure user-installed binaries are on PATH
ENV PATH="/root/.local/bin:${PATH}"

# Set workdir
WORKDIR /app

# Install Python dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy application source
COPY ./src .

# Run the DB initialization script
CMD ["python", "models_sql.py"]
